postgresql:
  replicaCount: 3
  maxConnections: 200
  podAntiAffinityPreset: hard
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
  # Persistence MUST be at this indentation level
persistence:
  enabled: true
  size: 20Gi
  storageClass: "iscsi-dell-me5-imd"

pgpool:
  replicaCount: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
